baseURL = 'http://avsr-io.github.io'
languageCode = 'en-us'
title = 'Avsr -- Using AI to create equal opportunities for all'
# theme = 'virgo'


[params]
    author = '???'

    en = false

    dark = false

    isSingleColumnOfPostList = true

    hasActiveAnimate = true

    hasActiveCool = false

    hasFoldAllCodeBlocks = false

    # Menu
    # -----------------------------------
    # Nav - nav.md or nav/index.md 
    # Search - search.md or search/index.md
    # Archive - archive.md or archive/index.md
    # Wiki - posts/wiki.md or wiki/index.md
    # About - about.md or about/index.md
    # -----------------------------------
    [params.menu]
        [params.menu.00]
            active = false
            path = '/nav'
            en = 'Nav'
            icon = 'ğŸ¯'
        [params.menu.11]
            active = false
            path = '/search'
            en = 'Search'
            icon = 'ğŸ”'
        [params.menu.22]
            active = false
            path = '/posts'
            en = 'Posts'
            icon = 'ğŸ“œ'
        [params.menu.33]
            active = false
            path = '/archive'
            en = 'Archive'
            icon = 'ğŸ‰'
        [params.menu.44]
            active = false
            path = '/posts/wiki'
            en = 'Wiki'
            zh = 'ç™¾ç§‘'
            icon = 'ğŸš€'
        [params.menu.55]
            active = false
            path = '/about'
            en = 'About'
            zh = 'å…³äº'
            icon = 'ğŸŒ' 
    
    [params.img]
        src = 'tux.jpg'
        width = 999
        words = "Stay hungry, Stay foolish. <br>Your time is limited, so don't waste it living someone else's life. <br>Have the courage to follow your heart and intuition. They somehow already know what you truly want to become."

    [params.contact]
        # twitter = 'loveminimal'             # e.g. https://twitter.com/loveminimal
        # facebook = 'loveminimal'            # e.g. https://facebook.com/loveminimal
        # youtube = 'loveminimal'             # e.g. https://youtube.com/user/loveminimal
        # telegram = 'https://web.telegram.org/z/'
    
# Markdown
[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        style = "github"
        lineNos = false
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
